# Generated by Django 2.2.6 on 2019-10-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Product_Info',
            },
        ),
    ]
